version: '3.8'
services:
  app:
    build: .
    ports:
      - "8081:8081"
    volumes:
      - .:/app
    environment:
      app.name: OrderService
    networks:
      - local-sub-net



networks:
  local-sub-net:
    driver: bridge